### ISSUE TITLE
Bug in gauss renderer

### ISSUE THREAD

**Issue by sethgi** [hbb1/torch-splatting#10]
Hello,

This is a great project, really makes prototyping features in splatting much easier!

I found that in order for the project to run, I had to change this line: https://github.com/hbb1/torch-splatting/blob/85c362152883cda066d6a1cc949c2bab7e2cc1c7/gaussian_splatting/gauss_render.py#L209C1-L210C1

from 

```
T = torch.cat([torch.ones_like(alpha[:,:1]), 1-alpha[:,-1:]], dim=1).cumprod(dim=1)
```

to:

```
T = torch.cat([torch.ones_like(alpha[:,:1]), 1-alpha[:,:-1]], dim=1).cumprod(dim=1)
``` 

Basically, just changing the indexing on the second alpha from [:,-1:] to [:, :-1].

Not sure if this is something just on my machine - but this got rid of a mismatched shape error on the next line. I also think the version I proposed matches the [original implementation](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d/cuda_rasterizer/forward.cu#L346C19-L346C20).

**Comment by hbb1** [comment]
Thank you, this is actually a bug occurring in my latest commit.
