### ISSUE TITLE
adaptive gaussian number

### ISSUE THREAD

**Issue by liuyuex97** [hbb1/torch-splatting#4]
Awesome repo! Are there any plans for implementing the adaptive control of the gaussians? If I want to implement it myself, what files should I look at in particular? Thanks.

**Comment by hbb1** [comment]
You should mainly modify the gaussian_model.py. Here is the reference, https://github.com/graphdeco-inria/gaussian-splatting/blob/main/scene/gaussian_model.py 

Note that the current torch implementation is computationally-expensive for real applications. In case you need to train your model in real application, you may replace the gaussian renderer with the official gaussian_renderer (CUDA implementation).

**Comment by liuyuex97** [comment]
Thanks for pointing the direction -  Yeah it seems computationally expensive with my tests but for now, I'm not too concerned with real application.
