### ISSUE TITLE
How is the training data generated from pointcloud?

### ISSUE THREAD

**Issue by liuyuex97** [hbb1/torch-splatting#5]
Hi are there any plans to release the code for generating the training images from point cloud? Thanks!

Edit: Did you by any chance use this Blender tool? https://blendermarket.com/products/blendernerf

**Comment by hbb1** [comment]
Hi, I actually use the script from here https://github.com/openai/point-e/blob/main/point_e/evals/scripts/blender_script.py.  
I will update the scripts later.

**Comment by liuyuex97** [comment]
I see. Thanks a lot for sharing!

**Comment by liuyuex97** [comment]
Just following up as a quick question, are the poses generated from this compatible with the original nerf's synthetic data? ie: https://drive.google.com/drive/folders/13kQggMKvKDvB6v9amHZfjENyZRIdHF1L

**Comment by hbb1** [comment]
I am not sure. You can check the Camera class. I guess it gives all you need to convert to nerf's synthetic data (focal, pose, ...).

**Comment by liuyuex97** [comment]
Okay I'll do some digging from there. Thanks a lot!
