### ISSUE TITLE
No module named 'simple_knn'

### ISSUE THREAD

**Issue by charliewalker322** [hbb1/torch-splatting#9]
I have installed simple_knn-1.1.6 by "pip install simple_knn", but the wrong " No module named 'simple_knn' " still exists.
What can i do to fix it?

**Comment by charliewalker322** [comment]
I have found the solution:
Download the package from https://gitlab.inria.fr/bkerbl/simple-knn and use pip to install it

**Comment by remmel** [comment]
Here is some code to get rid of simple_knn instead https://github.com/hbb1/torch-splatting/commit/fd1c9bfa7e56b60d8cb8510b9895b4b6c3f0d6c9
